apiVersion: v1
kind: Service
metadata:
  name: modality-api-service
spec:
  type: NodePort
  ports:
    - port: <port>        # The port where the service is accessible within the cluster
      nodePort: <port>   # The external port to access your service
      targetPort: <port>  # The internal port on the pod where your application listens
  selector:
    app: modality-api

